### ISSUE TITLE
Dynamic property must also @objc

### ISSUE THREAD

**Issue by techmehra** [essentiaone/Essentia-iOS#85]
![Screenshot 2019-04-22 at 3 13 43 PM](https://user-images.githubusercontent.com/18284379/56494861-59fb4680-6511-11e9-9bc4-ca705e9bbdda.png)
![Screenshot 2019-04-22 at 3 13 52 PM](https://user-images.githubusercontent.com/18284379/56494862-59fb4680-6511-11e9-8c91-00040ead95e9.png)

Xcode version 10.2.1

**Comment by impul** [comment]
@techmehra , we using Xcode 10.1.

**Comment by techmehra** [comment]
okay

**Comment by impul** [comment]
@techmehra, we updated the project to Xcode 10.2.1.
